# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 星辰大海
subtitle: My Conquest Is the Sea of Stars.
description: The King is dead, long live the King!
keywords: tech
author: vincent
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://vincentruan.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:vincentruan/vincentruan.github.io.git
  branch: master

# algolia:
#   applicationID: 085Q2989Y8
#   apiKey: 245c3b151c43ac65989ab011c1382e9d
#   indexName: hexo_vincentruan_starocean
#   chunkSize: 5000

search:
  path: search.xml
  field: post
  format: html
  limit: 10000
# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # enable: false
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    # use: live2d-widget-model-shizuku # npm-module package name
    use: xiaomai # 博客根目录/live2d_models/ 下的目录名 Attention! The path of the model's json must be /live2d_models/{name}/{name}.model.json
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://raw.githubusercontent.com/honjun/live2d-model/master/live2d/model/xiaomai/xiaomai.json # 你的自定义 url
  display:
    position: left
    width: 280
    height: 375
  mobile:
    show: false # 手机中是否展示
# hexo sitemap网站地图
baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml
  rel: false
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true